defaults: #points to sub-configs
  - model: xgboost_native.yaml  # knn.yaml, xgboost_native.yaml
  - _self_ # main overrides sub-cfg in case of duplicates

# EXPERIMENT CONFIG
#####################################################################

# NOTE: hydra configs are not passed on to cfg and don't need schema
hydra:
  run:
    dir: ./experiments/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./experiments/hydra_outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

experiment:
  save_model: False
  seed: 42
  train_fraction: 0.75
  features: ['Depth (m)', 'qc (MPa)', 'fs (kPa)','Rf (%)', 'σ,v (kPa)', 'u0 (kPa)',"σ',v (kPa)", 'Qtn (-)', 'Fr (%)']
  site_info: ['ID', 'test_type', 'basin_valley']
  label: 'Oberhollenzer_classes'
  undersample_level: 110000
  oversample_level: 75000
  soil_classification:
    1: gravel
    4: sand to gravel
    5: sand
    3: coarse grained organic soils
    2: fine grained organic soils
    6: silt to fine sand
    7: clay to silt

preprocess:
  outlier_feature: 'qc (MPa)'
  remove_duplicates: True
  remove_outliers_hard: True
  remove_outliers_uni: False
  remove_outliers_multi: False
  univariate_threshold: 3
  multivariate_threshold: 0.5


dataset:
  path_raw: ./data/raw/
  path_intermediate: ./data/intermediate
  path_model_ready: ./data/model_ready
  path_raw_dataset: ${dataset.path_raw}/CPT_PremstallerGeotechnik_revised.csv
  path_model_ready_train: ${dataset.path_model_ready}/dataset_train.csv
  path_model_ready_test: ${dataset.path_model_ready}/dataset_test.csv

mlflow:
  path: ./experiments/mlruns
  experiment_name: null # is set when calling scripts

optuna:
  n_trials: 5
  path_results: experiments/hyperparameters
